language: node_js
sudo: false
os: osx
node_js:
  - "10.10.0"
branches:
 only:
   - master
install:
  - npm install
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
script:
  - node ./node_modules/.bin/tslint "src/**/*.ts"  "src/**/*.tsx"
  - npm test


